name:         Dan Chao | dchao.co
description:  dan's blog
url:          http://dchao.co/
markdown:     redcarpet
permalink:    pretty
paginate:     8
links:
  - name:     About
    url:      /about
# gems: [activesupport]